security:
    encoders:
        # echo -n "test" | md5sum
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:
            - ROLE_USER
            - ROLE_PROJECT_ADMIN
            - ROLE_TESTCASE_ADMIN
        ROLE_SUPER_ADMIN:
            - ROLE_USER
            - ROLE_ADMIN
            - ROLE_ALLOWED_TO_SWITCH
        ROLE_TESTCASE_ADMIN:
            - ROLE_TESTCASE_USER

    providers:
        in_memory:
            memory:
                users:
                    admin:
                        password: test
                        roles: [ 'ROLE_ADMIN' ]

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        secured_area:
            pattern: ^/
            anonymous: ~

            form_login:
                login_path: tmt_project_index
                check_path: tmt_login_check

            logout:
                path: tmt_logout
                target: /

    access_control:
        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }