tmt_testcase:
    resource: "@TmtTestCaseBundle/Controller/TestCaseController.php"
    type:     annotation
tmt_test:
    resource: "@TmtTestCaseBundle/Controller/TestController.php"
    type:     annotation
tmt_useragent:
    resource: "@TmtTestCaseBundle/Controller/UserAgentController.php"
    type:     annotation
